import '../../../core/model/preference_option.dart';
import '../model/recipe.dart';

/// The seed catalogue shipped with the app and written to Firestore on first
/// launch, so the planner has something to plan from before any content
/// pipeline exists.
abstract final class RecipeCatalogue {
  static const fusilli = Recipe(
    id: 'fusilli_pois_lard_ricotta',
    title: 'Fusilli aux petits pois, au lard et à la ricotta',
    photoKey: 'fettucine',
    macros: Macros(kcal: 753, protein: 35, carbs: 97, fat: 25),
    cookTime: '20-25m',
    servings: 1,
    price: 5.20,
    cravingId: 'high_protein',
    ingredients: [
      Ingredient(icon: '🍝', name: 'Fusilli', quantity: '100g'),
      Ingredient(icon: '🫛', name: 'Petits pois', quantity: '60g'),
      Ingredient(icon: '🥓', name: 'Lardons', quantity: '37.5g'),
      Ingredient(icon: '🧀', name: 'Ricotta', quantity: '50g'),
      Ingredient(icon: '🧄', name: 'Ail', quantity: '½ gousse'),
      Ingredient(icon: '🍋', name: 'Citron (demi)', quantity: '¼'),
      Ingredient(icon: '🧈', name: 'Parmesan', quantity: '15g'),
    ],
    steps: [
      "Portez à ébullition une grande casserole d'eau salée et faites cuire les fusilli selon les instructions figurant sur l'emballage jusqu'à ce qu'ils soient al dente.",
      "Pendant ce temps, coupez le lard en petits morceaux, hachez finement l'ail et râpez finement le zeste du citron.",
      "Faites chauffer une grande poêle à feu moyen-vif. Ajoutez le lard et faites-le cuire 4 à 5 minutes jusqu'à ce qu'il soit doré et croustillant sur les bords.",
      "Baissez légèrement le feu, ajoutez l'ail et faites cuire brièvement jusqu'à ce qu'il soit parfumé.",
      "Ajoutez les petits pois aux pâtes pour les 2 à 3 dernières minutes de cuisson, jusqu'à ce qu'ils soient tendres et d'un vert éclatant.",
      "Réservez une tasse d'eau de cuisson, puis égouttez les fusilli et les petits pois.",
      "Baissez le feu de la poêle, ajoutez la ricotta, le zeste de citron et un filet d'eau de cuisson. Mélangez jusqu'à obtenir une sauce lisse et crémeuse.",
      "Ajoutez les fusilli et les petits pois, puis mélangez le tout jusqu'à ce qu'il soit bien enrobé, en ajoutant un peu plus d'eau de cuisson si nécessaire.",
      "Râpez le parmesan et incorporez-en la majeure partie jusqu'à obtenir un enrobage uniforme.",
      "Retirez du feu et ajoutez généreusement de poivre noir. Goûtez avant d'ajouter du sel, car le lard et le parmesan assaisonneront déjà généreusement.",
      "Répartissez dans des bols et servez.",
      "Terminez avec le parmesan restant.",
    ],
  );

  /// The seven dinners the planner draws from, in the order the design shows them.
  static const recipes = <Recipe>[
    Recipe(
      id: 'riz_poulet_cajun',
      title: 'Riz au poulet à la cajun',
      photoKey: 'cajun',
      macros: Macros(kcal: 612, protein: 41, carbs: 72, fat: 16),
      cookTime: '25m',
      servings: 1,
      price: 4.98,
      cravingId: 'quick',
      ingredients: [
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '1'),
        Ingredient(icon: '🥣', name: "Mélange d'épices cajun", quantity: '½ c. à s.'),
        Ingredient(icon: '🫑', name: 'Poivrons grillés au barbecue', quantity: '95g'),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🫒', name: "Huile d'olive", quantity: '1 c. à s.'),
      ],
      steps: [
        "Faites cuire le riz dans une casserole d'eau bouillante salée selon les instructions de l'emballage.",
        "Coupez le poulet en lanières et enrobez-le du mélange d'épices cajun.",
        "Faites chauffer l'huile dans une poêle à feu vif et saisissez le poulet 6 à 8 minutes jusqu'à ce qu'il soit bien coloré.",
        "Ajoutez l'oignon rouge émincé et les poivrons, puis faites revenir 3 minutes.",
        "Égouttez le riz, incorporez-le à la poêle et mélangez bien.",
        "Rectifiez l'assaisonnement et servez immédiatement.",
      ],
    ),
    Recipe(
      id: 'nouilles_tofu_satay',
      title: 'Nouilles au tofu et au satay',
      photoKey: 'noodle',
      macros: Macros(kcal: 684, protein: 32, carbs: 78, fat: 27),
      cookTime: '25m',
      servings: 1,
      price: 5.39,
      cravingId: 'high_protein',
      ingredients: [
        Ingredient(icon: '🍜', name: 'Nouilles', quantity: '90g'),
        Ingredient(icon: '🧈', name: 'Tofu extra-ferme', quantity: '150g'),
        Ingredient(icon: '🥜', name: 'Beurre de cacahuètes', quantity: '20g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🍈', name: 'Citron vert', quantity: '½'),
        Ingredient(icon: '🧅', name: 'Cébette', quantity: '2 tiges'),
      ],
      steps: [
        "Pressez le tofu pour en extraire l'excès d'eau, puis coupez-le en cubes.",
        "Faites dorer le tofu dans une poêle chaude 6 à 8 minutes en le retournant régulièrement.",
        "Faites cuire les nouilles selon les instructions de l'emballage, puis égouttez-les.",
        "Mélangez le beurre de cacahuètes, la sauce soja, le jus de citron vert et un peu d'eau chaude pour obtenir une sauce satay lisse.",
        "Réunissez les nouilles, le tofu et la sauce dans la poêle et mélangez à feu doux.",
        "Parsemez de cébette émincée et servez.",
      ],
    ),
    Recipe(
      id: 'boites_riz_poulet_piment_doux',
      title: 'Boîtes de riz au poulet au piment doux',
      photoKey: 'handi',
      macros: Macros(kcal: 598, protein: 44, carbs: 70, fat: 13),
      cookTime: '25m',
      servings: 1,
      price: 4.98,
      cravingId: 'quick',
      ingredients: [
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '1'),
        Ingredient(icon: '🌶️', name: 'Sauce au piment doux', quantity: '20ml'),
        Ingredient(icon: '🥦', name: 'Brocoli', quantity: '120g'),
        Ingredient(icon: '🥕', name: 'Carottes', quantity: '65g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
      ],
      steps: [
        "Faites cuire le riz et laissez-le refroidir légèrement.",
        "Coupez le poulet en morceaux et faites-le saisir jusqu'à ce qu'il soit doré.",
        "Ajoutez la sauce au piment doux et la sauce soja, puis laissez glacer 2 minutes.",
        "Faites cuire le brocoli et les carottes à la vapeur jusqu'à ce qu'ils soient tendres mais croquants.",
        "Répartissez le riz, le poulet et les légumes dans des boîtes hermétiques.",
        "Conservez au réfrigérateur jusqu'à trois jours.",
      ],
    ),
    Recipe(
      id: 'farfalle_feta_feves',
      title: 'Farfalle à la feta et aux fèves',
      photoKey: 'pasta',
      macros: Macros(kcal: 671, protein: 29, carbs: 86, fat: 24),
      cookTime: '25m',
      servings: 1,
      price: 6.81,
      cravingId: 'high_protein',
      ingredients: [
        Ingredient(icon: '🎀', name: 'Farfalle', quantity: '95g'),
        Ingredient(icon: '🧀', name: 'Feta', quantity: '50g'),
        Ingredient(icon: '🫘', name: 'Fèves surgelées', quantity: '125g'),
        Ingredient(icon: '🍋', name: 'Citron', quantity: '½'),
        Ingredient(icon: '🌿', name: 'Persil', quantity: '20g'),
        Ingredient(icon: '🫒', name: "Huile d'olive", quantity: '1½ c. à s.'),
      ],
      steps: [
        "Faites cuire les farfalle dans une grande casserole d'eau salée jusqu'à ce qu'elles soient al dente.",
        "Ajoutez les fèves pour les 3 dernières minutes de cuisson.",
        "Réservez un peu d'eau de cuisson, puis égouttez.",
        "Émiettez la feta dans un saladier avec l'huile d'olive, le zeste et le jus de citron.",
        "Mélangez les pâtes chaudes avec la feta en ajoutant un filet d'eau de cuisson pour lier.",
        "Parsemez de persil haché et servez.",
      ],
    ),
    Recipe(
      id: 'riz_frit_poulet',
      title: 'Riz frit au poulet',
      photoKey: 'friedrice',
      macros: Macros(kcal: 627, protein: 38, carbs: 74, fat: 18),
      cookTime: '25m',
      servings: 1,
      price: 4.98,
      cravingId: 'quick',
      ingredients: [
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '1'),
        Ingredient(icon: '🥚', name: 'Œufs', quantity: '1'),
        Ingredient(icon: '🫛', name: 'Pois', quantity: '40g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
      ],
      steps: [
        "Faites cuire le riz la veille si possible — un riz froid donne le meilleur résultat.",
        "Coupez le poulet en dés et saisissez-le dans un wok très chaud.",
        "Ajoutez l'ail haché et les pois, puis faites sauter 2 minutes.",
        "Poussez le tout sur un côté du wok, cassez l'œuf et brouillez-le rapidement.",
        "Ajoutez le riz et la sauce soja, puis faites sauter à feu vif 3 à 4 minutes.",
        "Servez sans attendre.",
      ],
    ),
    Recipe(
      id: 'carbonara_haricots_asperges',
      title: "Carbonara aux haricots beurre et aux asperges à l'ail",
      photoKey: 'carbonara',
      macros: Macros(kcal: 742, protein: 34, carbs: 68, fat: 36),
      cookTime: '35m',
      servings: 1,
      price: 7.65,
      cravingId: 'quick',
      ingredients: [
        Ingredient(icon: '🫘', name: 'Haricots beurre', quantity: '½ boîte'),
        Ingredient(icon: '🌿', name: "Pointes d'asperges", quantity: '50g'),
        Ingredient(icon: '🥓', name: 'Pancetta non fumée', quantity: '42.5g'),
        Ingredient(icon: '🥚', name: "Jaunes d'œufs", quantity: '1'),
        Ingredient(icon: '🧈', name: 'Parmesan', quantity: '20g'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
      ],
      steps: [
        "Faites revenir la pancetta à feu moyen jusqu'à ce qu'elle soit croustillante.",
        "Ajoutez l'ail émincé et les asperges coupées en tronçons, puis faites cuire 4 minutes.",
        "Égouttez et rincez les haricots beurre, puis réchauffez-les dans la poêle.",
        "Battez le jaune d'œuf avec le parmesan râpé et beaucoup de poivre noir.",
        "Retirez la poêle du feu, incorporez le mélange d'œuf et un filet d'eau chaude en remuant sans cesse.",
        "Servez dès que la sauce nappe les haricots.",
      ],
    ),
    Recipe(
      id: 'ragout_haricots_chorizo',
      title: 'Ragoût de haricots beurre au chorizo',
      photoKey: 'stew',
      macros: Macros(kcal: 588, protein: 30, carbs: 54, fat: 27),
      cookTime: '35m',
      servings: 1,
      price: 5.75,
      cravingId: 'quick',
      ingredients: [
        Ingredient(icon: '🫘', name: 'Haricots beurre', quantity: '1 boîte'),
        Ingredient(icon: '🌭', name: 'Chorizo', quantity: '50g'),
        Ingredient(icon: '🥫', name: 'Tomates coupées en morceaux', quantity: '100ml'),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🌶️', name: 'Piment rouge', quantity: '1'),
        Ingredient(icon: '🌿', name: 'Persil', quantity: '10g'),
      ],
      steps: [
        "Faites rendre le chorizo coupé en dés dans une cocotte à feu moyen.",
        "Ajoutez l'oignon émincé et le piment, puis faites suer 5 minutes.",
        "Versez les tomates concassées et laissez mijoter 10 minutes.",
        "Ajoutez les haricots beurre égouttés et poursuivez la cuisson 8 minutes.",
        "Rectifiez l'assaisonnement — le chorizo sale déjà le plat.",
        "Parsemez de persil et servez avec du pain.",
      ],
    ),
    fusilli,
    Recipe(
      id: 'soupe_lasagnes_boeuf',
      title: 'Soupe aux lasagnes au bœuf',
      photoKey: 'lasagne',
      macros: Macros(kcal: 564, protein: 33, carbs: 52, fat: 22),
      cookTime: '20m',
      servings: 1,
      price: 5.10,
      cravingId: 'healthy_comfort',
      ingredients: [
        Ingredient(icon: '🥩', name: 'Bœuf haché', quantity: '125g'),
        Ingredient(icon: '🥫', name: 'Tomates coupées en morceaux', quantity: '200ml'),
        Ingredient(icon: '🍝', name: 'Feuilles de lasagne', quantity: '2'),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
        Ingredient(icon: '🧀', name: 'Ricotta', quantity: '40g'),
      ],
      steps: [
        "Faites colorer le bœuf haché dans une cocotte à feu vif.",
        "Ajoutez l'oignon et l'ail, puis faites revenir 4 minutes.",
        "Versez les tomates et 400ml d'eau, puis portez à frémissement.",
        "Cassez les feuilles de lasagne en morceaux et ajoutez-les au bouillon.",
        "Laissez mijoter 10 minutes jusqu'à ce que les pâtes soient tendres.",
        "Servez avec une cuillère de ricotta au centre.",
      ],
    ),
    Recipe(
      id: 'poulet_saute_sesame',
      title: 'Poulet sauté au sésame',
      photoKey: 'sesame',
      macros: Macros(kcal: 605, protein: 42, carbs: 58, fat: 21),
      cookTime: '22m',
      servings: 1,
      price: 5.45,
      cravingId: 'fakeaway',
      ingredients: [
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '1'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🥦', name: 'Brocoli', quantity: '110g'),
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
        Ingredient(icon: '🫓', name: 'Graines de sésame', quantity: '1 c. à s.'),
      ],
      steps: [
        "Faites cuire le riz et réservez-le au chaud.",
        "Coupez le poulet en lanières fines et saisissez-le dans un wok très chaud.",
        "Ajoutez l'ail et le brocoli, puis faites sauter 4 minutes.",
        "Versez la sauce soja et laissez réduire une minute.",
        "Faites torréfier les graines de sésame à sec et parsemez-en le plat.",
        "Servez sur le riz chaud.",
      ],
    ),
  ];

  /// Recipes matching the "recently viewed" rail in the design.
  static const recentIds = <String>[
    'soupe_lasagnes_boeuf',
    'fusilli_pois_lard_ricotta',
    'poulet_saute_sesame',
  ];

  static const cuisines = <Cuisine>[
    Cuisine(id: 'italian', name: 'Italienne', description: 'Pasta • Risotto • Gnocchi', photoKey: 'lasagne'),
    Cuisine(id: 'asian', name: 'Asiatique', description: 'Nouilles • Curry • Sauté', photoKey: 'noodle'),
    Cuisine(id: 'mexican', name: 'Mexicaine', description: 'Tacos • Burritos • Fajitas', photoKey: 'chilli'),
    Cuisine(id: 'indian', name: 'Indienne', description: 'Curry • Tikka • Tandoori', photoKey: 'curry'),
    Cuisine(id: 'mediterranean', name: 'Méditerranéenne', description: 'Gyros • Halloumi • Falafel', photoKey: 'kebab'),
  ];

  /// Recipes the planner may schedule, keyed by the craving they satisfy.
  static List<Recipe> forCravings(Set<Craving> cravings) {
    final ids = cravings.map((c) => c.id).toSet();
    final matching = recipes.where((r) => ids.contains(r.cravingId)).toList();
    return matching.isEmpty ? recipes : matching;
  }

  static Recipe? byId(String id) => recipes.where((r) => r.id == id).firstOrNull;
}
