import '../../../core/model/preference_option.dart';
import '../model/recipe.dart';

/// The bundled recipe catalogue, taken verbatim from the design. It is the
/// single source of truth: the planner, search, filters and favourites all
/// read from here.
abstract final class RecipeCatalogue {
  static const recipes = <Recipe>[
    Recipe(
      id: 'riz_poulet_cajun',
      title: 'Riz au poulet à la cajun',
      photoKey: 'cajun',
      macros: Macros(kcal: 612, protein: 41, carbs: 74, fat: 16),
      time: '25m',
      cookTime: '20-25m',
      price: 4.98,
      craving: Craving.quick,
      protein: RecipeProtein.chicken,
      ingredients: [
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '150g'),
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(
          icon: '🥣',
          name: "Mélange d'épices cajun",
          quantity: '½tbsp',
        ),
        Ingredient(icon: '🫑', name: 'Poivron', quantity: '1'),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
        Ingredient(icon: '🫒', name: "Huile d'olive", quantity: '1tbsp'),
      ],
      steps: [
        "Faites cuire le riz selon les instructions de l'emballage.",
        "Coupez le poulet en dés et enrobez-le du mélange d'épices cajun.",
        "Émincez le poivron et l'oignon, hachez l'ail.",
        "Saisissez le poulet 6 à 8 minutes dans une poêle chaude jusqu'à ce qu'il soit doré et cuit à cœur.",
        "Ajoutez les légumes et l'ail, faites revenir 4 minutes.",
        "Mélangez le riz à la poêlée, rectifiez l'assaisonnement et servez.",
      ],
    ),
    Recipe(
      id: 'nouilles_tofu_satay',
      title: 'Nouilles au tofu et au satay',
      photoKey: 'noodle',
      macros: Macros(kcal: 698, protein: 38, carbs: 71, fat: 29),
      time: '25m',
      cookTime: '20-25m',
      price: 5.39,
      craving: Craving.highProtein,
      protein: RecipeProtein.tofu,
      cuisine: Cuisine.asian,
      ingredients: [
        Ingredient(icon: '🍜', name: 'Nouilles', quantity: '90g'),
        Ingredient(icon: '🧈', name: 'Tofu extra-ferme', quantity: '150g'),
        Ingredient(icon: '🥜', name: 'Beurre de cacahuètes', quantity: '20g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🍈', name: 'Citron vert', quantity: '½'),
        Ingredient(icon: '🥕', name: 'Carottes', quantity: '65g'),
        Ingredient(icon: '🧅', name: 'Cébette', quantity: '2 tiges'),
      ],
      steps: [
        'Égouttez le tofu et coupez-le en cubes.',
        "Faites cuire les nouilles, puis rincez-les à l'eau froide.",
        "Mélangez le beurre de cacahuètes, la sauce soja, le jus de citron vert et un peu d'eau chaude pour obtenir la sauce satay.",
        'Faites dorer le tofu 8 minutes sur toutes ses faces.',
        'Ajoutez les carottes en julienne et faites revenir 2 minutes.',
        'Mélangez nouilles, tofu et sauce, parsemez de cébette.',
      ],
    ),
    Recipe(
      id: 'boites_riz_poulet_piment_doux',
      title: 'Boîtes de riz au poulet au piment doux',
      photoKey: 'handi',
      macros: Macros(kcal: 640, protein: 43, carbs: 78, fat: 15),
      time: '25m',
      cookTime: '20-25m',
      price: 4.98,
      craving: Craving.quick,
      protein: RecipeProtein.chicken,
      cuisine: Cuisine.asian,
      ingredients: [
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '150g'),
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🌶️', name: 'Sauce au piment doux', quantity: '20ml'),
        Ingredient(icon: '🥦', name: 'Brocoli', quantity: '100g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '1 gousse'),
      ],
      steps: [
        'Faites cuire le riz et laissez-le refroidir légèrement.',
        'Coupez le poulet en lanières.',
        'Faites-le saisir 7 minutes, puis nappez-le de sauce au piment doux et de sauce soja.',
        'Faites cuire le brocoli à la vapeur 4 minutes.',
        'Répartissez riz, poulet et brocoli dans des boîtes.',
        'Laissez refroidir avant de fermer et de réfrigérer.',
      ],
    ),
    Recipe(
      id: 'farfalle_feta_feves',
      title: 'Farfalle à la feta et aux fèves',
      photoKey: 'pasta',
      macros: Macros(kcal: 684, protein: 31, carbs: 88, fat: 23),
      time: '25m',
      cookTime: '20-25m',
      price: 6.81,
      craving: Craving.highProtein,
      protein: RecipeProtein.vegetarian,
      cuisine: Cuisine.italian,
      ingredients: [
        Ingredient(icon: '🎀', name: 'Farfalle', quantity: '95g'),
        Ingredient(icon: '🧀', name: 'Feta', quantity: '50g'),
        Ingredient(icon: '🫘', name: 'Fèves surgelées', quantity: '125g'),
        Ingredient(icon: '🍋', name: 'Citron', quantity: '½'),
        Ingredient(icon: '🌿', name: 'Persil', quantity: '10g'),
        Ingredient(icon: '🫒', name: "Huile d'olive", quantity: '1½tbsp'),
      ],
      steps: [
        'Faites cuire les farfalle en eau bouillante salée.',
        'Ajoutez les fèves dans les 3 dernières minutes de cuisson.',
        "Réservez un peu d'eau de cuisson, puis égouttez.",
        "Écrasez la moitié de la feta avec l'huile d'olive, le zeste et le jus de citron.",
        "Mélangez les pâtes à la sauce en ajoutant l'eau de cuisson par filets.",
        'Parsemez du reste de feta et du persil ciselé.',
      ],
    ),
    Recipe(
      id: 'riz_frit_poulet',
      title: 'Riz frit au poulet',
      photoKey: 'friedrice',
      macros: Macros(kcal: 623, protein: 39, carbs: 76, fat: 17),
      time: '25m',
      cookTime: '20m',
      price: 4.98,
      craving: Craving.quick,
      protein: RecipeProtein.chicken,
      cuisine: Cuisine.asian,
      ingredients: [
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '150g'),
        Ingredient(icon: '🥚', name: 'Œufs', quantity: '1'),
        Ingredient(icon: '🫛', name: 'Pois', quantity: '40g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '15ml'),
        Ingredient(icon: '🧅', name: 'Cébette', quantity: '2 tiges'),
      ],
      steps: [
        'Utilisez du riz cuit la veille, bien froid.',
        'Coupez le poulet en dés et faites-le dorer à feu vif.',
        "Poussez le poulet sur le côté, brouillez l'œuf dans la poêle.",
        'Ajoutez le riz et les pois, faites sauter 3 minutes sans trop remuer.',
        'Versez la sauce soja et mélangez le tout.',
        'Terminez avec la cébette émincée.',
      ],
    ),
    Recipe(
      id: 'carbonara_haricots_asperges',
      title: "Carbonara aux haricots beurre et aux asperges à l'ail",
      photoKey: 'carbonara',
      macros: Macros(kcal: 742, protein: 34, carbs: 69, fat: 36),
      time: '35m',
      cookTime: '30-35m',
      price: 7.65,
      craving: Craving.quick,
      protein: RecipeProtein.pork,
      cuisine: Cuisine.italian,
      ingredients: [
        Ingredient(icon: '🫘', name: 'Haricots beurre', quantity: '200g'),
        Ingredient(icon: '🥓', name: 'Pancetta non fumée', quantity: '42.5g'),
        Ingredient(icon: '🌿', name: "Pointes d'asperges", quantity: '50g'),
        Ingredient(icon: '🥚', name: "Jaunes d'œufs", quantity: '1'),
        Ingredient(icon: '🧈', name: 'Parmesan', quantity: '20g'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '1 gousse'),
      ],
      steps: [
        "Faites dorer la pancetta jusqu'à ce qu'elle soit croustillante.",
        "Ajoutez l'ail et les asperges, faites cuire 3 minutes.",
        'Égouttez et rincez les haricots beurre, puis ajoutez-les à la poêle.',
        "Battez le jaune d'œuf avec le parmesan râpé.",
        "Hors du feu, incorporez le mélange en remuant avec un filet d'eau chaude.",
        'Poivrez généreusement et servez aussitôt.',
      ],
    ),
    Recipe(
      id: 'ragout_haricots_chorizo',
      title: 'Ragoût de haricots beurre au chorizo',
      photoKey: 'stew',
      macros: Macros(kcal: 588, protein: 29, carbs: 58, fat: 26),
      time: '35m',
      cookTime: '30-35m',
      price: 5.75,
      craving: Craving.quick,
      protein: RecipeProtein.pork,
      cuisine: Cuisine.mediterranean,
      ingredients: [
        Ingredient(icon: '🫘', name: 'Haricots beurre', quantity: '200g'),
        Ingredient(icon: '🌭', name: 'Chorizo', quantity: '50g'),
        Ingredient(
          icon: '🥫',
          name: 'Tomates coupées en morceaux',
          quantity: '100ml',
        ),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
        Ingredient(icon: '🌿', name: 'Persil', quantity: '10g'),
      ],
      steps: [
        'Faites rendre sa graisse au chorizo coupé en dés.',
        "Ajoutez l'oignon émincé et faites-le fondre 5 minutes.",
        "Ajoutez l'ail, puis les tomates, et laissez réduire 10 minutes.",
        'Incorporez les haricots beurre égouttés et laissez mijoter 8 minutes.',
        "Rectifiez l'assaisonnement.",
        'Parsemez de persil avant de servir.',
      ],
    ),
    Recipe(
      id: 'soupe_lasagnes_boeuf',
      title: 'Soupe aux lasagnes au bœuf',
      photoKey: 'lasagne',
      macros: Macros(kcal: 566, protein: 35, carbs: 52, fat: 22),
      time: '20m',
      cookTime: '20m',
      price: 5.20,
      craving: Craving.quick,
      protein: RecipeProtein.beef,
      cuisine: Cuisine.italian,
      ingredients: [
        Ingredient(icon: '🥩', name: 'Bœuf haché', quantity: '125g'),
        Ingredient(
          icon: '🥫',
          name: 'Tomates coupées en morceaux',
          quantity: '200ml',
        ),
        Ingredient(icon: '🍝', name: 'Feuilles de lasagne', quantity: '2'),
        Ingredient(icon: '🧅', name: 'Oignon rouge', quantity: '½'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '2 gousses'),
        Ingredient(icon: '🧀', name: 'Parmesan', quantity: '15g'),
      ],
      steps: [
        'Faites colorer le bœuf haché dans une casserole.',
        "Ajoutez l'oignon et l'ail, faites revenir 4 minutes.",
        "Versez les tomates et 400 ml d'eau, portez à ébullition.",
        'Cassez les feuilles de lasagne en morceaux et ajoutez-les.',
        "Laissez cuire 8 à 10 minutes jusqu'à ce que les pâtes soient tendres.",
        'Servez avec du parmesan râpé.',
      ],
    ),
    Recipe(
      id: 'fusilli_pois_lard_ricotta',
      title: 'Fusilli aux petits pois, au lard et à la ricotta',
      photoKey: 'fettucine',
      macros: Macros(kcal: 753, protein: 35, carbs: 97, fat: 25),
      time: '25m',
      cookTime: '20-25m',
      price: 5.60,
      craving: Craving.highProtein,
      protein: RecipeProtein.pork,
      cuisine: Cuisine.italian,
      ingredients: [
        Ingredient(icon: '🍝', name: 'Fusilli', quantity: '100g'),
        Ingredient(icon: '🫛', name: 'Petits pois', quantity: '60g'),
        Ingredient(icon: '🥓', name: 'Lardons', quantity: '37.5g'),
        Ingredient(icon: '🧀', name: 'Ricotta', quantity: '50g'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '½ gousse'),
        Ingredient(icon: '🍋', name: 'Citron', quantity: '¼'),
        Ingredient(icon: '🧈', name: 'Parmesan', quantity: '15g'),
      ],
      steps: [
        "Portez à ébullition une grande casserole d'eau salée et faites cuire les fusilli jusqu'à ce qu'ils soient al dente.",
        "Coupez le lard en petits morceaux, hachez l'ail et râpez le zeste du citron.",
        "Faites cuire le lard 4 à 5 minutes jusqu'à ce qu'il soit doré et croustillant.",
        "Baissez le feu, ajoutez l'ail et faites cuire jusqu'à ce qu'il soit parfumé.",
        'Ajoutez les petits pois aux pâtes pour les 3 dernières minutes de cuisson.',
        "Réservez une tasse d'eau de cuisson, puis égouttez.",
        "Ajoutez la ricotta, le zeste et un filet d'eau de cuisson pour obtenir une sauce crémeuse.",
        'Mélangez les pâtes à la sauce, incorporez le parmesan et poivrez généreusement.',
      ],
    ),
    Recipe(
      id: 'wraps_big_mac',
      title: 'Wraps façon Big Mac',
      photoKey: 'bigmac',
      macros: Macros(kcal: 712, protein: 38, carbs: 46, fat: 41),
      time: '25m',
      cookTime: '20-25m',
      price: 6.40,
      craving: Craving.indulgent,
      protein: RecipeProtein.beef,
      creator: "C'est Tarpin Bon",
      ingredients: [
        Ingredient(icon: '🥫', name: 'Moutarde', quantity: '1 c. à café'),
        Ingredient(icon: '🥣', name: 'Mayonnaise', quantity: '2 c. à café'),
        Ingredient(icon: '🍅', name: 'Ketchup', quantity: '2 c. à café'),
        Ingredient(icon: '🥒', name: 'Cornichons', quantity: 'au goût'),
        Ingredient(icon: '🥒', name: 'Jus de cornichons', quantity: '1 filet'),
        Ingredient(
          icon: '🌯',
          name: 'Mini crêpes (petits wraps)',
          quantity: '4',
        ),
        Ingredient(icon: '🥩', name: 'Bœuf haché cru', quantity: '400g'),
        Ingredient(icon: '🧂', name: 'Sel', quantity: 'au goût'),
        Ingredient(
          icon: '🫗',
          name: 'Spray de cuisson',
          quantity: '1 pulvérisation',
        ),
        Ingredient(icon: '🧀', name: 'Cheddar en tranches', quantity: '4'),
        Ingredient(icon: '🥬', name: 'Laitue', quantity: '½'),
      ],
      steps: [
        'Mélangez la moutarde, la mayonnaise, le ketchup, les cornichons et un peu de jus de cornichons pour faire la sauce Big Mac.',
        'Déposez le bœuf haché cru sur une mini crêpe et salez.',
        "Faites chauffer une poêle avec le spray de cuisson et faites cuire le bœuf d'un seul côté.",
        "Retournez le bœuf et ajoutez le cheddar, laissez cuire jusqu'à ce que le fromage fonde et que la viande soit dorée.",
        'Ajoutez de fines lamelles de cornichons sur la viande.',
        'Ajoutez la laitue et nappez généreusement de sauce Big Mac.',
        'Pliez ou roulez le wrap et servez.',
      ],
    ),
    Recipe(
      id: 'poulet_saute_sesame',
      title: 'Poulet sauté au sésame',
      photoKey: 'sesame',
      macros: Macros(kcal: 604, protein: 45, carbs: 58, fat: 19),
      time: '22m',
      cookTime: '20-22m',
      price: 5.20,
      craving: Craving.highProtein,
      protein: RecipeProtein.chicken,
      cuisine: Cuisine.asian,
      ingredients: [
        Ingredient(icon: '🍗', name: 'Poitrine de poulet', quantity: '150g'),
        Ingredient(icon: '🍚', name: 'Riz', quantity: '75g'),
        Ingredient(icon: '🍶', name: 'Sauce soja claire', quantity: '20ml'),
        Ingredient(icon: '🫓', name: 'Graines de sésame', quantity: '1tbsp'),
        Ingredient(icon: '🥦', name: 'Brocoli', quantity: '100g'),
        Ingredient(icon: '🧄', name: 'Ail', quantity: '1 gousse'),
      ],
      steps: [
        'Faites cuire le riz.',
        'Coupez le poulet en lanières et faites-le saisir à feu vif.',
        "Ajoutez l'ail et le brocoli, faites sauter 4 minutes.",
        'Versez la sauce soja et laissez glacer 1 minute.',
        'Faites torréfier les graines de sésame à sec.',
        'Parsemez-en le plat et servez avec le riz.',
      ],
    ),
  ];

  /// The "recently viewed" rail before the user has opened anything.
  static const recentIds = <String>[
    'soupe_lasagnes_boeuf',
    'fusilli_pois_lard_ricotta',
    'poulet_saute_sesame',
  ];

  static Recipe? byId(String id) =>
      recipes.where((r) => r.id == id).firstOrNull;
}
